"""Add is_logged_in column

Revision ID: 455cb0518d67
Revises: 
Create Date: 2025-04-21 00:45:21.277890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455cb0518d67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_id', table_name='product')
    op.drop_index('ix_product_product_id', table_name='product')
    op.drop_table('product')
    op.drop_index('ix_user_profile_email', table_name='user_profile')
    op.drop_index('ix_user_profile_id', table_name='user_profile')
    op.drop_index('ix_user_profile_name', table_name='user_profile')
    op.drop_table('user_profile')
    op.add_column('users', sa.Column('is_logged_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_logged_in')
    op.create_table('user_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profession', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_profile_pkey')
    )
    op.create_index('ix_user_profile_name', 'user_profile', ['name'], unique=False)
    op.create_index('ix_user_profile_id', 'user_profile', ['id'], unique=False)
    op.create_index('ix_user_profile_email', 'user_profile', ['email'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_quantity_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='product_pkey')
    )
    op.create_index('ix_product_product_id', 'product', ['product_id'], unique=False)
    op.create_index('ix_product_id', 'product', ['id'], unique=False)
    # ### end Alembic commands ###
